### ISSUE TITLE
educaas-ui error

### ISSUE THREAD

**Issue by mkscala** [dalareo/educaas-ui#3]
Hi ,
 I have cloned your educaas-ui and exe the below command and i get the error 
docker-compose up
/usr/local/bin/docker-compose:5: UserWarning: Module _markerlib was already imported from /Library/Python/2.7/site-packages/distribute-0.6.49-py2.7.egg/_markerlib/__init__.pyc, but /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python is being added to sys.path
  from pkg_resources import load_entry_point
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.7.0', 'console_scripts', 'docker-compose')()
  File "/Library/Python/2.7/site-packages/distribute-0.6.49-py2.7.egg/pkg_resources.py", line 345, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Library/Python/2.7/site-packages/distribute-0.6.49-py2.7.egg/pkg_resources.py", line 2381, in load_entry_point
    return ep.load()
  File "/Library/Python/2.7/site-packages/distribute-0.6.49-py2.7.egg/pkg_resources.py", line 2087, in load
    entry = **import**(self.module_name, globals(),globals(), ['**name**'])
  File "/Library/Python/2.7/site-packages/compose/cli/main.py", line 25, in <module>
    from ..project import NoSuchService
  File "/Library/Python/2.7/site-packages/compose/project.py", line 12, in <module>
    from . import parallel
  File "/Library/Python/2.7/site-packages/compose/parallel.py", line 10, in <module>
    from six.moves import _thread as thread
ImportError: cannot import name _thread

**Comment by donvito** [comment]
Try this, I think you need to reinstall docker-compose

curl -L https://github.com/docker/compose/releases/download/1.8.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose

chmod +x /usr/local/bin/docker-compose

**Comment by mkscala** [comment]
I will try it today
